- name: purge apache
  apt:
    name:
      - apache2
    state: absent
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: install various packages from debian repos
  apt:
    name:
      - apache2-utils
      - autofs
      - chromium
      - curl
      - gitk
      - htop
      - inkscape
      - intel-microcode
      - ldnsutils
      - mariadb-client
      - nginx
      - pass
      - peek
      - php
      - pwgen
      - rsync
      - screen
      - thunderbird
      - ufw
      - vlc
      - virt-manager
      - webext-browserpass
      - whois
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: add node key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    id: "68576280"
    state: present
  become: true
- name: add node repo
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_12.x buster main" # hardcode buster for now
    state: present
  become: true
- name: install node
  apt:
    name: nodejs
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: skip grub bootmenu
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_TIMEOUT="
    line: "GRUB_TIMEOUT=0"
  become: true
  notify: update grub
- name: increase number of file handlers
  copy:
    src: max_user_watches.conf
    dest: /etc/sysctl.d/max_user_watches.conf
    force: yes
  become: true
