- name: get installed packages
  package_facts:
- name: install packages from debian repos
  apt:
    name:
      - autofs
      - ca-certificates
      - chromium
      - curl
      - gnome
      - gnupg2
      - htop
      - hunspell-en-gb
      - info
      - mysql-client
      - mysql-server
      - nginx # TODO ensure that apache is not enabled on port 80
      - pass
      - php
      - prometheus-node-exporter
      - redshift-gtk # not necessary in the gnome3 that ships with the next version of Debian
      - software-properties-common
      - sudo
      - taskwarrior
      - timewarrior
      - thunderbird
      - enginmail
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: add apt keys
  apt_key:
    url: "{{ item.url }}"
    id: "{{ item.id }}"
    state: present
  with_items:
    - { url: 'https://packagecloud.io/AtomEditor/atom/gpgkey', id: 'DE9E3B09'}
    - { url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key', id: '68576280'}
  become: true
- name: add third party repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any any main"
    - "deb https://deb.nodesource.com/node_8.x {{ansible_distribution_release}} main"
  become: true
- name: install packages from third party repos
  apt:
    name:
      - atom
      - nodejs
    update_cache: true
    cache_valid_time: 3600
  become: true
# Principle: don't cater for people that don't follow the rules
# - name: install skype
#   apt:
#     deb: "https://repo.skype.com/latest/skypeforlinux-64.deb"
#   become: true
#   when: ansible_facts.packages.skypeforlinux is not defined
# note: mattermost will not automatically update :(
- name: get latest version of mattermost
  uri:
    url: "https://api.github.com/repos/mattermost/desktop/releases/latest"
    return_content: yes
  register: mattermost_latest_release
- name: install mattermost
  apt:
    deb: "https://releases.mattermost.com/desktop/{{ mattermost_latest_release.json.tag_name[1:] }}/mattermost-desktop-{{ mattermost_latest_release.json.tag_name[1:] }}-linux-amd64.deb"
  become: true
  when: ansible_facts.packages['mattermost-desktop'] is not defined
- name: skip grub bootmenu
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=0'
  become: true
  notify: update grub
