- name: git checkout of backup scripts
  git:
    repo: https://github.com/3sd/backup
    dest: /usr/local/src/backup
  become: true
- name: cron file to create local backups
  copy:
    src: cron_backup
    dest: /etc/cron.d/backup
  become: true
- name: Create required backup directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/backup
    - /srv/backup/local/now
  become: true
- name: default backup pattern
  copy:
    src: etc_backup_pattern
    dest: /etc/backup/pattern
    force: no
  become: true
