- name: git checkout of backup scripts
  git:
    repo: https://github.com/michaelmcandrew/backup
    dest: /usr/local/src/backup
  become: true
- name: cron file to create local backups
  copy:
    src: "cron_{{ item }}"
    dest: "/etc/cron.d/{{ item }}"
  become: true
  with_items:
    - pit
    - collect
