- name: install zsh and other required packages
  apt:
    name:
      - zsh
      - autojump
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: "set shell for {{ ansible_user }} to zsh"
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true
- name: git checkout of zsh config and plugins
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dir }}"
  with_items:
    - {
        url: "https://github.com/3sd/zsh.git",
        dir: "/home/{{ ansible_user }}/.zsh",
      }
    - {
        url: "https://github.com/zsh-users/zsh-autosuggestions",
        dir: "/home/{{ ansible_user }}/.zsh/plugins/zsh-autosuggestions",
      }
    - {
        url: "https://github.com/zsh-users/zsh-history-substring-search",
        dir: "/home/{{ ansible_user }}/.zsh/plugins/zsh-history-substring-search",
      }
    - {
        url: "https://github.com/zsh-users/zsh-completions",
        dir: "/home/{{ ansible_user }}/.zsh/plugins/zsh-completions",
      }
    - {
        url: "https://github.com/starcraftman/zsh-git-prompt",
        dir: "/home/{{ ansible_user }}/.zsh/plugins/zsh-git-prompt",
      }
- name: symlink to zsh config
  file:
    src: "/home/{{ ansible_user }}/.zsh/zshrc"
    dest: "/home/{{ ansible_user }}/.zshrc"
    state: link
- name: copy zsh vars to host
  template:
    src: zsh_vars
    dest: "/home/{{ ansible_user }}/.zsh/vars"
