- name: add apt keys
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    id: DE9E3B09
    state: present
  become: true
- name: add third party repos
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any any main
    state: present
  become: true
- name: install atom
  apt:
    name:
      - atom
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: install pip
  apt:
    name:
      - python-pip
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: install sqlparse
  pip:
    name: sqlparse
