- name: remove apache
  apt:
    name:
      - apache
    update_cache: true
    state: absent
    purge: yes
    cache_valid_time: 3600
  become: true
- name: install lemp for civicrm
  apt:
    name:
      - nginx
      - mysql-server
      - mysql-client
      - php
    update_cache: true
    cache_valid_time: 3600
  become: true
