- name: install docker and docker-compose
  apt:
    name:
      - docker.io
      - docker-compose
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: "add {{ ansible_user }} to docker group"
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker
  become: true
