- name: apt install some utilities
  apt:
    name:
      - git
      - htop
      - vim
      - prometheus-node-exporter
      - ldnsutils
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: disable password authentication for ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication no
  become: true
  notify: restart sshd
- name: prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
  become: true
