- name: apt install some essential packages
  apt:
    name:
      - apt-transport-https
      - git
      - htop
      - vim
      - prometheus-node-exporter
      - ldnsutils
    update_cache: true
    cache_valid_time: 3600
  become: true
- name: disable password authentication for ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication no
  become: true
  notify: restart sshd
